Q1.  Convert a 1-D array into a 2-D array with 3 rows. 
Start with: 
Assign-1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]) 
Desired output: 
[[ 0, 1, 2] 
[3, 4, 5] 
[6, 7, 8]]

Q2.  Replace all odd numbers in the given array with -1 
Start with: 
Assign-2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
Desired output: 
[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

Q3.  Find the positions of elements in x where its value is more than its corresponding element in y, and elements in x where its value is 
equals to its corresponding element in y. 
Start with these: 
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])  
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18]) 
Desired output: 
(array([1, 2, 4, 5, 6, 7, 8, 9]),) and (array([0]),) 

Q4. . Extract the first four columns of this 2-D array. 
Start with this:  
Assign-4= np.arange(100).reshape(5,-1) 
Desired output: 
[[ 0 1 2 3] 
[20 21 22 23] 
[40 41 42 43] 
[60 61 62 63] 
[80 81 82 83]]