# CSV Files

Reading CSV Files 

In [1]:
# import necessary modules

import csv
with open('data.csv','rt') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['Programming language', 'Designed by', 'Appeared', 'Extension']
['Python', 'Guido van Rossum', '1991', ' .py ']
['Java', ' James Gosling', '1995', ' .java']
['C++', 'Bjarne Stroustrup', '1983', '.cpp']


In [2]:
reader = csv.DictReader(open('data.csv','rt'))
for raw in reader:
    print(raw)

{'Programming language': 'Python', 'Designed by': 'Guido van Rossum', 'Appeared': '1991', 'Extension': ' .py '}
{'Programming language': 'Java', 'Designed by': ' James Gosling', 'Appeared': '1995', 'Extension': ' .java'}
{'Programming language': 'C++', 'Designed by': 'Bjarne Stroustrup', 'Appeared': '1983', 'Extension': '.cpp'}


Writing CSV Files

In [3]:
with open('data1.csv','w') as file:
    writer = csv.writer(file, delimiter=',', quotechar='"',quoting=csv.QUOTE_MINIMAL)
    writer.writerow(['Programming language', 'Designed by', 'Appeared', 'Extension'])
    writer.writerow(['Python', 'Guido van Rossum', '1991', ' .py '])
    writer.writerow(['Java', ' James Gosling', '1995', ' .java'])
    writer.writerow(['C++', 'Bjarne Stroustrup', '1983', '.cpp'])

Reading CSV Files with Pandas

In [4]:
# import necessary modules

import pandas
result = pandas.read_csv('data1.csv')
print(result)

  Programming language        Designed by  Appeared Extension
0               Python   Guido van Rossum      1991      .py 
1                 Java      James Gosling      1995     .java
2                  C++  Bjarne Stroustrup      1983      .cpp


Writing CSV Files With Pandas 

In [5]:
from pandas import DataFrame
C={'Programming Language':['Python','Java','C++'], 
   'Designed by':['Guido Van Rossum','James Gosling','Bjarne Stroupstrup'],
   'Appeared':[1991, 1995, 1985],
   'Extension':['.py','.java','.cpp'],
}
df = DataFrame(C,columns=['Programming Language','Designed by','Appeared','Extension'])
export_csv = df.to_csv('data2.csv',index=None,header=True)
print(df)

  Programming Language         Designed by  Appeared Extension
0               Python    Guido Van Rossum      1991       .py
1                 Java       James Gosling      1995     .java
2                  C++  Bjarne Stroupstrup      1985      .cpp


# NumPy

The Basics

In [6]:
import numpy as np 
a = np.arange(15).reshape(3, 5) 
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape 

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.dtype.name 

'int32'

In [10]:
a.itemsize 

4

In [11]:
a.size 

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8]) 
b

array([6, 7, 8])

In [14]:
type(b) 

numpy.ndarray

Array Creation

In [15]:
a = np.array([2, 3, 4]) 
a

array([2, 3, 4])

In [16]:
a.dtype 

dtype('int32')

In [17]:
b = np.array([1.2, 3.5, 5.1])
b.dtype 

dtype('float64')

In [18]:
b = np.array([(1.5, 2, 3), (4, 5, 6)]) 
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [19]:
c = np.array([[1, 2], [3, 4]], dtype=complex) 
c 

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [20]:
np.empty((2, 3))  # Array of uninitialized (arbitrary) data of the given shape, dtype, and order is returned

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
np.arange(10, 30, 5) 

array([10, 15, 20, 25])

In [22]:
np.arange(0, 2, 0.3)               # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
np.linspace(0, 2, 9)               # 9 numbers from 0 to 2 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
from numpy import pi
x = np.linspace(0, 2 * pi, 10) # useful to evaluate a function at lots of points 
np.sin(x)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

Printing Arrays

In [25]:
a = np.arange(6)                    # 1d array
a 

array([0, 1, 2, 3, 4, 5])

In [26]:
b = np.arange(12).reshape(4, 3)     # 2d array 
b 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array (lists of matrices)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Basic Operations

In [28]:
a = np.array([20, 30, 40, 50]) 
b = np.arange(4) 
b

array([0, 1, 2, 3])

In [29]:
c = a - b 
c

array([20, 29, 38, 47])

In [30]:
b**2 

array([0, 1, 4, 9])

In [31]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [32]:
a < 35 

array([ True,  True, False, False])

In [33]:
A = np.array([[1, 1], 
              [0, 1]]) 
B = np.array([[2, 0], 
              [3, 4]]) 

A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [34]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [35]:
A.dot(B)  # another way to do matrix product

array([[5, 4],
       [3, 4]])

In [36]:
rg = np.random.default_rng(1)  # create instance of default random number generator 
a = np.ones((2, 3), dtype=int) 
b = rg.random((2, 3)) 
a *= 3 
a

array([[3, 3, 3],
       [3, 3, 3]])

In [37]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [38]:
a += b  # b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [39]:
a = np.ones(3, dtype=np.int32) 
b = np.linspace(0, pi, 3) 
b.dtype.name

'float64'

In [40]:
c = a + b 
c

array([1.        , 2.57079633, 4.14159265])

In [41]:
c.dtype.name

'float64'

In [42]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [43]:
a = rg.random((2, 3)) 
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [44]:
a.sum()

3.1057109529998157

In [45]:
a.min()

0.027559113243068367

In [46]:
a.max()

0.8277025938204418